### PR TITLE
Added export date range + extra configurations

### PR DESCRIPTION
**Pull request by sitecorepm**
Hi,

I added the ability to export for a given date range. I also added more configuration options such as whether to use the export range functionality or the original.

Rebuilt package + updated version to 1.3... although i now see I should have made it 1.4

Thoughts?

### CODE REVIEW

**Comment by TakeitEasyAlan** [comment]
Hi,

Thanks, I forgot to write that in version 1.3 I added a column that contains the timestamp for when the form was submitted.

Just been on holiday for a week, and before that I was ill for a week so i am a bit booked up this week but hopefully this weekend I will review and merge what you have done and make a 1.4 release :-)

cheers for the work contribution, Alan

**Comment by sitecorepm** [comment]
Hi Alan,

Sounds like you need another week of holiday!

I also should have mentioned how I changed the default export
functionality. When you click the export toolbar button now it opens the
export page which has the date range options and an export button.
Also, the exported columns are delimited with commas "," instead of
semi-colons ";".

The original functionality can be restored by changing the new config
settings: "WFFM.SQLServer.SaveToDatabase.CsvDelimiter",
"WFFM.SQLServer.SaveToDatabase.ExportOptions" accordingly.

Paul

**Comment by TakeitEasyAlan** [comment]
Hi,

I will merge in the changes, will set the default delimited to be ; so it opens in excel nicely .-)

But otherwise thanks for the contribution, and I will release it soon on the Market place :-) 

Cheers, Alan

**Comment by sitecorepm** [comment]
Hey Alan,

Great thanks!

That's weird. When I open it in Excel 2013 with the ";" delimiter it opens
but everything is in a single column. When I use the "," delimiter it works
as expected.

Paul

**Comment by TakeitEasyAlan** [comment]
Maybe its a danish thing, but ; works for me :-) 

But thanks for making it configurable so people can choose, the module was only meant to be a quick fix until people moved to xDB but I have more and more customers that don't want to make the move.

Friday bar has started over here so its best I don't release anything now :-)

**Comment by sitecorepm** [comment]
Enjoy! Cheers!

**Comment by TakeitEasyAlan** [comment]
Hi,

I have made the changes (now in the main branch) and submitted them to the market place (which can take anything from 1 hour to a week to get published), but when it is published I will announce the changes with a small blog post (and of course give you the credit for the work :-)

Once again thanks for the contribution :-)

I've also moved the config from app_data to app_config/include (can see that I was a bit busy when I created the module as there are a lot of stupid small spelling mistakes, etc)

**Pull request merged**
